#
###################################
# Site wide configuration
####################################
#
title: My notes
email:
description: My notes
url: /notes # the base hostname & protocol for your site
keywords: ["blog", "jekyll", "notes"]
hide:
  home: false
  archive: false
  categories: false
  resume: false
  tags: true
  navigation: true
navigation:
  left:
#    icon: fa-angle-left
    icon: fa-arrow-left
    color: danger
  home:
#    icon: fa-leaf
    icon: fa-home
    color: warning
  right:
#    icon: fa-angle-right
    icon: fa-arrow-right
    color: success

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Rome
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: My notes
  avatar: leonids-logo.png
  job: 
  bio: 
  email:
  disqus-shortname:
  twitter: abilardi #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: bilardi #username
  gitlab: #username
  stackoverflow: 1472538 #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: bilardi #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
  wikipedia: Bilardi #username
  custom:
    - url: http://github.com/renyuanz/leonids/
      icon: fa-code-fork

webrick:
  headers:
    Access-Control-Allow-Origin: "*"

style:
  text:
    color: rgba(0, 0, 0, 0.87)
  author:
    color: "#F36170"
  background:
    color: "#f5f5f5"
    image: https://s3-eu-west-1.amazonaws.com/cdn.bilardi.net/alessandra/index/background.jpg #http://domain.name/path/background.jpg
    size: cover
  color:
    white: "#fff"
    primary: "#42b983"
    secondary: rgba(0, 0, 0, 0.87)
    success: "#65e892"
    danger: "#f83e4b"
    warning: "#F5A623"
    info: "#09ABF6"
